const types = {
    ADD_TOKEN: "ADD_TOKEN",
    ADD_ERROR: "ADD_ERROR",
    ADD_EMAIL: "ADD_EMAIL",
    LOAD_USER_STATS: "LOAD_USER_STATS",
    ADD_NAME: "ADD_NAME",
    MODIFY_SHIP_LENGTH: "MODIFY_SHIP_LENGTH",
    MODIFY_SELECTED_SQUARES: "MODIFY_SELECTED_SQUARES",
    MODIFY_SHIP_ORIENTATION: "MODIFY_SHIP_ORIENTATION",
    UPDATE_LAST_ACTIVE_SQUARE: "UPDATE_LAST_ACTIVE_SQUARE"
}

export default types;