const types = {
    ADD_TOKEN: "ADD_TOKEN",
    ADD_ERROR: "ADD_ERROR",
    UPDATE_USER_WINS: "UPDATE_USER_WINS",
    UPDATE_USER_LOSSES: "UPDATE_USER_LOSSES",
    LOAD_USER_INFO: "LOAD_USER_INFO",
    MODIFY_SHIP_LENGTH: "MODIFY_SHIP_LENGTH",
    MODIFY_SELECTED_SQUARES: "MODIFY_SELECTED_SQUARES",
    MODIFY_SHIP_ORIENTATION: "MODIFY_SHIP_ORIENTATION",
    UPDATE_LAST_ACTIVE_SQUARE: "UPDATE_LAST_ACTIVE_SQUARE",
    UPDATE_SHIP_LOCATIONS: "UPDATE_SHIP_LOCATIONS",
    DELETE_SHIP_LENGTH: "DELETE_SHIP_LENGTH",
    RESET_GAME_BOARD: "RESET_GAME_BOARD",
    START_GAME: "START_GAME",
    UPDATE_SHIP_COORDINATES: "UPDATE_SHIP_COORDINATES",
    DELETE_FROM_SHIP_COORDINATES: "DELETE_FROM_SHIP_COORDINATES",
    FLIP_USER_MISS: "FLIP_USER_MISS",
    RESET_GAME: "RESET_GAME",
    NEXT_COMPUTER_MOVE: "NEXT_COMPUTER_MOVE",
    UPDATE_SHIP_INDEX: "UPDATE_SHIP_INDEX",
    DELETE_USER_SHIP_COORDINATE: "DELETE_USER_SHIP_COORDINATE",
    UPDATE_LAST_HIT: "UPDATE_LAST_HIT",
    SET_MESSAGE: "SET_MESSAGE"
}

export default types;